fix bug for camera not pausing in scales mode
portugueslab/sashimi pull request #122
Opened 2021-02-18 14:18 UTC by kkoetter

Changed the toggling between `camera_loop` and `pause_loop` in `CameraProcess` to avoid camera getting stuck in camera loop for the mock camera. Issue with `--scopeless `was that the Camera was just entering `pause_loop` at initialisation of the GUI and afterwards was in `camera_loop` without a return. Code needs to be tested with hamamatsu camera to verify changes didn't crash anything. There are multiple `CameraMode` that are created but never checked such as `TRIGGERED`, `EXPERIMENT_RUNNING`. Could this potentially be simplified?

2021-02-18 15:18 UTC, kkoetter commented
Update: Tested with hamamatsu in the light sheet computer. No apparent problems so far.

2021-02-18 16:00 UTC, vigji requested changes

2021-02-18 21:53 UTC, vilim approved these changes
Looks good, after these few changes it can be merged!

2021-02-18 21:53 UTC, vilim commented on sashimi/processes/camera.py
> +    #TRIGGERED = 2
There should be no modes that are not used, and no commented lines

2021-02-18 21:53 UTC, vilim commented on sashimi/processes/camera.py
> +            self.camera.start_acquisition()
Also please remove the commented lines and write a small comment why the pause_loop is enough (basically inside of it the `if` you removed above is implemented.

2021-02-19 09:10 UTC, kkoetter commented
I now have removed the unnecessary `CameraMode`s and restructured the logger into the `camera_loop` and `pause_loop` to clean up the `run_camera` function. If thee is no more changes requested I would be happy for someone to review it again :)

2021-02-19 09:21 UTC, vigji approved these changes

2021-02-19 09:47 UTC, merged